spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/slackinhousebot
    username: root
    password: 2115
  jpa:
    properties:
      hibernate:
        ddl: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
logging.level:
  com.slack.api: DEBUG
server:
  port: 3000
secret:
  token:
    bot-oauth: xoxb-
    user-oauth: xoxp-