spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/slackinhousebot
    username: root
    password: 2115
  jpa:
    properties:
      hibernate:
        ddl: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
logging.level:
  com.slack.api: DEBUG
server:
  port: 3000
secret:
  token:
    bot-oauth: xoxb-3269430670614-3269535316726-Kbc84GLuKYd7cbUMds9HI7dP
    user-oauth: xoxp-3269430670614-3276080348819-3266887577927-b225649bacb357e95ec6d57a31d1a427